name: Continuous Integration

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'plugins/**'

jobs:
  Prettier:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.FORCE_PUSH }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17

      # Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm i -g prettier && npm i

      - name: Run Prettier
        run: prettier --write plugins/*.ts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "style: run prettier"
          commit_options: '--no-verify --signoff'
          repository: .
          commit_user_name: "GitHub Actions"
          status_options: '--untracked-files=no'
          push_options: '--force'
